### ISSUE TITLE
Fact_find é uma tabela vazia

### ISSUE THREAD

**Issue by dan195794** [pianeiro/unisinos-bi-big-data#1]
O job está apagando a tabela quando junta o airline id.

**Comment by pianeiro** [comment]
Olá, @dan195794 ;

Vou verificar à noitinha.

**Comment by pianeiro** [comment]
@dan195794 ;

Bug consertado pelo commit 187a50cc02b0f68f1923849b74e139bc12aafe36. Por algum motivo, a dimensão airline estava com 3 caracteres de cumprimento, gerando um espaço à direita que impedia merge.
